// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by the Game Data Editor.
//
//      Changes to this file will be lost if the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;

namespace GameDataEditor
{
    public class GDEItemKeys
    {
        public static string WeaponAttribute_Gun0_Power = "Gun0_Power";
        public static string WeaponAttribute_Gun0_MaxZoom = "Gun0_MaxZoom";
        public static string WeaponAttribute_Gun0_Stability = "Gun0_Stability";
        public static string WeaponAttribute_Gun0_Capacity = "Gun0_Capacity";
        public static string WeaponAttribute_Gun0_Infrared = "Gun0_Infrared";
        public static string Weapon_Gun0 = "Gun0";
        public static string Weapon_Gun0_4c74319fd77f42c9b2133b6ca2cc33e7 = "Gun0_4c74319fd77f42c9b2133b6ca2cc33e7";
    }
}
